name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test-go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@master
      - name: Use Go 1.21.3
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
          cache-dependency-path: ./go.sum
      - name: Test
        run: go test ./...
