# list all available commands
default:
    @just --list

# This justfile contains helpful commands for testing astria-go.

# get balances of all genesis accounts
get-all-balances:
    #!/bin/sh
    # used shebang to run the script in a subshell to only require single `cd ..`
    cd ../modules/cli
    echo "Balances for 1c0c490f1b5528d8173c5de46d131160e4b2c0c3"
    go run main.go sequencer balances 1c0c490f1b5528d8173c5de46d131160e4b2c0c3
    echo "Balances for 34fec43c7fcab9aef3b3cf8aba855e41ee69ca3a"
    go run main.go sequencer balances 34fec43c7fcab9aef3b3cf8aba855e41ee69ca3a
    echo "Balances for 60709e2d391864b732b4f0f51e387abb76743871"
    go run main.go sequencer balances 60709e2d391864b732b4f0f51e387abb76743871
    echo "Balances for 3ac486d3cd14cdc69633afe2dd170bdb093cd81a"
    go run main.go sequencer balances 3ac486d3cd14cdc69633afe2dd170bdb093cd81a
alias gab := get-all-balances

# get all nonces of genesis accounts
get-all-nonces:
    #!/bin/sh
    # used shebang to run the script in a subshell to only require single `cd ..`
    cd ../modules/cli
    go run main.go sequencer nonce --json 1c0c490f1b5528d8173c5de46d131160e4b2c0c3
    go run main.go sequencer nonce --json 34fec43c7fcab9aef3b3cf8aba855e41ee69ca3a
    go run main.go sequencer nonce --json 60709e2d391864b732b4f0f51e387abb76743871
    go run main.go sequencer nonce --json 3ac486d3cd14cdc69633afe2dd170bdb093cd81a
alias gan := get-all-nonces

# make transfer with privkey for account 1c0c490f1b5528d8173c5de46d131160e4b2c0c3
tx:
    #!/bin/sh
    # used shebang to run the script in a subshell to only require single `cd ..`
    cd ../modules/cli
    go run main.go sequencer transfer 53000000 3ac486d3cd14cdc69633afe2dd170bdb093cd81a \
        --privkey=2bd806c97f0e00af1a1fc3328fa763a9269723c8db8fac4f93af71db186d6e90 \
        --log-level=debug

# to test huge transaction that sends 2^64 tokens
tx-huge:
    #!/bin/sh
    # used shebang to run the script in a subshell to only require single `cd ..`
    cd ../modules/cli
    go run main.go sequencer transfer 18446744073709551616 3ac486d3cd14cdc69633afe2dd170bdb093cd81a \
        --privkey=2bd806c97f0e00af1a1fc3328fa763a9269723c8db8fac4f93af71db186d6e90 \
        --log-level=debug --json
