default:
  @just --list

set dotenv-load
set fallback

run-cometbft:
    ./cometbft init --home ../data/.cometbft
    cp genesis.json ../data/.cometbft/config/genesis.json
    cp priv_validator_key.json ../data/.cometbft/config/priv_validator_key.json
    sed -i '.bak' 's/timeout_commit = "1s"/timeout_commit = "2s"/g' ../data/.cometbft/config/config.toml
    ./cometbft node --home ../data/.cometbft

run-sequencer:
    ./astria-sequencer

run-conductor:
    ./astria-conductor

run-composer:
    ./astria-composer

clean:
    rm -rf ~/.cometbft/
    rm -rf /tmp/astria_db
