on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-for-release:
    name: Build For Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: "linux"
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: >
            -X github.com/astria/astria-cli-go/cmd.version=${{ github.ref_name }}
          project_path: "./"
          binary_name: "astria-go"
