name: Build For Release

# Build `astria-go` binaries for multiple architectures whenever
# a release is created, using the tag name as the cli's version

on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-for-release:
    name: Build For Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: "linux"
    steps:
      - uses: actions/checkout@v4
      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          ldflags: >
            -s -w -X github.com/astriaorg/astria-cli-go/modules/cli/cmd.version=${{ github.ref_name }}
          project_path: "./modules/cli"
          binary_name: "astria-go"
