on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  build-for-release:
    name: Build For Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: "arm64"
            goos: "linux"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build binary with debug info
        run: |
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build \
          -o astria-go-debug-${{ matrix.goos }}-${{ matrix.goarch }} -gcflags "all=-N -l" \
          -ldflags "-X github.com/astria/astria-cli-go/cmd.version=${{ github.ref_name }}" .

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
            name: astria-go-${{ matrix.goos }}-${{ matrix.goarch }}
            path: astria-go-${{ matrix.goos }}-${{ matrix.goarch }}
