name: Lint & Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
          cache-dependency-path: ./go.sum
      - name: Lint Go
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-pulls: false
      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.json
          dot: true
      - name: Test Go
        # FIXME - the ProcessPane tests require tty or pty i think.
        #  no solutions have worked so far https://github.com/actions/runner/issues/241
        run: go test ./... -skip TestProcessPane
