name: Lint & Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
          cache-dependency-path: ./go.sum
      - name: Lint Go & Markdown
        uses: super-linter/super-linter@v6.4.1
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: true
          VALIDATE_MARKDOWN: true
      - name: Test Go
        # FIXME - the ProcessPane tests require tty or pty i think.
        #  no solutions have worked so far https://github.com/actions/runner/issues/241
        run: go test ./... -skip TestProcessPane
