name: Lint & Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install just
        uses: taiki-e/install-action@just
      - uses: actions/setup-go@v4
        with:
          go-version: 1.22.0
          cache-dependency-path: ./go.sum
      - name: Lint Go (cli)
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: modules/cli
          version: latest
          skip-pulls: false
      - name: Lint Go (go-sequencer-client)
        uses: golangci/golangci-lint-action@v2
        with:
          working-directory: modules/go-sequencer-client
          version: latest
          skip-pulls: false
      - name: Lint Markdown
        uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
          config_file: .markdownlint.json
          dot: true
      - name: Test Go (cli)
        # FIXME - the ProcessPane tests require tty or pty i think.
        #  no solutions have worked so far https://github.com/actions/runner/issues/241
        run: go test ./... -skip TestProcessPane
        working-directory: modules/cli
      - name: Integration Test Go
        run: |
          # run dev runner and test-integration
          just run dev init
          screen -d -m just run dev run
          sleep 5
          just test-integration
# FIXME - sequencer client tests are empty
#      - name: Test Go (go-sequencer-client)
#        run: go test ./...
#        working-directory: modules/go-sequencer-client
