name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Go 1.21.3
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
          cache-dependency-path: ./go.sum
      - name: Test
        # FIXME - the ProcessPane tests require tty or pty i think.
        #  no solutions have worked so far https://github.com/actions/runner/issues/241
        run: go test ./... -skip TestProcessPane
