name: Test

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Go 1.21.3
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.3
          cache-dependency-path: ./go.sum
      - name: Test
        # GitHub Actions run without a TTY device. This is a workaround to get one,
        # based on https://github.com/actions/runner/issues/241#issuecomment-842566950.
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: go test ./...
